server:
  port: 8080
  servlet:
    context-path: /identity

spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root  
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 

jwt:
  signerKey: "4Z3K1l+aYWcOWA7m10vgWrpIoHHOzwczPQVFE9qmGTadVYeaS/RjSN5z9C+f3ytk"
